package.json

Currently we have several custom npm commands for creating releases. This is not ideal and also clutters our commit history (makes two commits for every release). I realized these are unnecessary after learning you can add to the `npm version` command by adding a `version` script. This means we can use the built in `npm version` command and have it automatically include the updated changelog in the version commit. 
This means we will no longer have multi commit releases like this
But a single version commit like we had before.

Chore: Update the changelog when `npm version` is run

---

demo/router/routeRecordsFlat.ts
demo/sections/concurrency/ConcurrencyLimitDetails.vue
demo/sections/concurrency/ConcurrencyLimitsTable.vue

There was an error in the demo because the workspace routes were being included in the context sidebar search

Chore: Fix the demo routes and clean up

---

src/services/can.ts

delete:workspace should be account permission

chore: permission string audit

---

package-lock.json
package.json
src/styles/style.css
vite.config.ts

Upgrading vite and @vitejs/plugin-vue
~~Does not appear to need the `cssCodeSplit` turned off like prefect-design did. Which I believe is due to the tailwind base styles coming from prefect design.~~ Noticed some issues with the demo after a second look. Turning off `cssCodeSplit` fixed those issues. 
Also remove the fontsource packages from this repo since they were already coming from prefect-design

Chore: Update vite and clean up fonts

---

src/index.ts

The introduction of the pixi-viewport package introduces a `window` reference into the global scope of this package. This causes orion-design to be unusable in a node context. 
The integration tests in orion-ui use orion-design's mocks and apis for test fixtures in node. So this allows us to continue with integration tests without solving the underlying issue of isolation components from raw js code.

Chore: Fix the umd bundle

---

src/components/NotificationsTable.vue

We need some way to identify individual notifications in the DOM in order to use text fixtures in the orion-ui integration tests. A simple yet effective way is to add the notification id as a data attribute.

Chore: Add data attribute to identify notifications in the dom by their id

---

demo/App.vue
src/compositions/useCan.ts
src/services/can.ts

this puts down the framework to define flags in orion-design (as well as in nebula/orion-ui still).
flags can be defined in orion-design if they are planned to be implemented in both nebula and orion-ui
defining a can in nebula will be the combination of
- orion-design "WorkspacePermission"
- orion-design "FeatureFlags"
- nebula-ui "AccountPermission"
- nebula-ui "FeatureFlags"
defining a can in orion-ui will be the combination of 
- orion-design "WorkspacePermission"
- orion-design "FeatureFlags"
- orion-ui "FeatureFlags"

Feature: ready to support flags defined in orion-design

---

package-lock.json
package.json
vite.config.ts

We've had some issues with both prefect-design and vue-compositions not playing nicely across orion-design and orion-ui/nebula-ui. Thinks like subscriptions not being shared and messed up UI styles for tables. 
prefect-design was already a peer dependency but vue-compositions was not. They both should be peers so I updated vue-compositions to be a peer. 
Any peer dependencies must also be marked as external in the vite config otherwise they will be bundle with orion-design when it is published. 
Making them both external dependencies in the PR with removes them from the bundle and imports them directly from whatever project orion-design is added too. This makes the bundle smaller but more importantly should fix the above mentioned issues. 
I can verify the subscription sharing but is …

Chore: Fix dependency duplication 

---

src/services/schemas/utilities.ts

Because of how definitions work for nested blocks, sometimes we have to guess what the definition is. If we cannot guess we try and safely fallback. A check was missing in the fallback that was causing it to error. 
Closes https://github.com/PrefectHQ/orion-design/issues/979
Note: This doesn't solve the issue that we sometimes cannot guess the correct definition. Specifically if a property is a union of two blocks we're unable to guess because the value is a guid.

BugFix: Prevent errors when guessing the definition for a schema property value. 

---

src/components/ParametersTable.vue
src/components/SchemaFormFields.vue
src/components/SchemaPropertiesKeyValues.vue
src/types/schemas.ts

Decided against doing this in the mapper since it would fundamentally change the data being passed around and instead added sorting to the form fields component. 
Resolves: https://github.com/PrefectHQ/prefect/issues/7508
cc @j-tr

Enhancement: Add optional position to schema properties, sort schema form fields

---

package-lock.json
package.json
src/components/FlowRunTimeline.vue
src/utilities/dates.ts

Update the graphs dependency to 0.1.9
The FlowRunTimeline graph now requires date formatting methods to be passed in. One is `format-time-by-minutes` which is intended for a short form time label when a series of times are listed by minute, and showing seconds adds no value. A time format was added for this use case.

update graphs dependency and add short time format

---

src/utilities/timezone.ts

this PR switches utc option to iana named timezone, which works for both date-fns-tz and also our API for things like deployment schedules
closes #1005

BugFix: utc timezone selection in deployment schedule

---

src/components/FlowRunListItem.vue
src/maps/flowRun.ts
src/mocks/flowRun.ts
src/models/FlowRun.ts
src/models/api/FlowRunResponse.ts
src/types/UnionFilters.ts

This PR adds WorkerPool name to the flowRun card. The goal is to show WorkQueue if there's no WorkerPool, and show WorkerPool even if WorkQueue exists

Enhancement: Add workerPool IconText to flowRun card

---

package-lock.json
package.json

Reverts to vue-compositions 1.1.2 because of suspected bugs in 1.1.3 and 1.2.0

Chore: Revert to vue-compositions 1.1.2

---

demo/sections/TimezoneSupport.vue
src/components/TimezoneSelect.vue

the timezone select uses the append slot to display an example of what the current time would be in the selected timezone. upon closer review, this doesn't make sense for situations where the timezone select is right next to a datepicker. The user would expect to A: be able to edit that time from here. B: expect the time to be the one selected from the other component, not the current time.
before:
after:

Feature: hide timestamp from TimezoneSelect by default

---

src/components/StateBadge.vue

In the final build base state classes have higher specificity than the classes coming from this component. Worth figuring out why that's the case but for now this will make sure this component renders properly.

Bugfix: Make state badge text color important

---

src/components/NotificationMenu.vue
src/components/NotificationsTable.vue

This PR hides the 3-dot menu if the user doesn't have permission to interact with it. Also, finally fixes alignment between menu and toggle
Closes https://github.com/PrefectHQ/orion-design/issues/919

Chore: Remove 3 dot menu on Notifications if the user doesn't have permission to edit/delete

---

src/components/BlockCapabilityBlockDocumentInput.vue

Solves an issue with migrating notifications over to automations where notifications use anonymous blocks. We don't want anonymous blocks to show up in the list but if the selected value is an anonymous block we can display it.

Enhancement: Support displaying an anonymous block in the BlockCapabilityBlockDocumentInput

---

src/components/DeploymentDetails.vue
src/components/IntervalScheduleForm.vue
src/components/TimezoneSelect.vue

Current behavior:
If I create an interval schedule and select "Use browser default" the timezone is sent as null, which the api interprets as UTC.  The timezone that is sent back is shown as UTC. 
Fix:
This adds the local timezone string to send the correct value to the api. 
I'd appreciate eyes on from @stackoverfloweth here as I know he did a lot of timezone work and I don't want this to mess any of that up!

BugFix: Hide browser default option when editing deployment schedules

---

src/utilities/httpStatus.ts

this function already does a lot of type guard checks, it just needed to loosen it's param type to enable the following syntax
```ts
try {
// something sketch
} catch(error) {
// typeof error here is `unknown`
if (httpStatus(error).is('Forbidden')) {
// now we know error is `AxiosError | AxiosResponse | number` and the status code was 403    
}
}
```

BugFix: loosen requirements to call httpStatus utility

---

src/components/WorkPoolQueueMenu.vue
src/components/WorkPoolQueueToggle.vue
src/components/WorkPoolQueuesTable.vue
src/router/routes.ts

The work pool queue components and pages will use the same permissions that work queues currently use. This PR is a small update to use the existing work queue permission for work pool queue pages and components.
Verified work pool queue creation, modification, and deletion with `nebula-ui` running against the staging API.

Chore: Updates permissions for work pool queue components and pages

---

src/components/SchemaFormInput.vue
src/components/SchemaPropertyKeyValue.vue
src/models/api/BlockDocumentCreateRequest.ts
src/services/schemas/properties/SchemaPropertyBlock.ts
src/services/schemas/resolvers/blockReferences.ts
src/services/schemas/utilities.ts
src/utilities/cache.ts

Fixes an issue with how references for blocks were being guessed based on the the value. Update the ui to always keep the block id and the block type slug together so anywhere in code we always know what type the block is. 
Before
After
Close https://github.com/PrefectHQ/orion-design/issues/979

BugFix: Cannot create block that has a union property of multiple blocks

---

src/components/BlocksPageEmptyState.vue
src/components/ConcurrencyLimitsPageEmptyState.vue
src/components/DeploymentDeprecatedMessage.vue
src/components/DeploymentDescriptionEmptyState.vue
src/components/DeploymentsPageEmptyState.vue
src/components/DocumentationButton.vue
src/components/FlowRunsPageEmptyState.vue
src/components/FlowsPageEmptyState.vue
src/components/NotificationsPageEmptyState.vue
src/components/WorkPoolsPageEmptyState.vue
src/components/WorkQueuesPageEmptyState.vue

Makes `DocumentationButton` component more generic by allowing string URLs to be passed in rather than keys of the `localization.docs` object. 
Updates all instances of `DocumentationButton` to use the new "to" prop, and pass in the appropriate string const from `localization.docs`
This contains no breaking changes for Orion UI, but does contain breaking changes for Nebula UI

Chore: replace DocumentionButton "topic" prop with "to" prop

---

src/components/WorkPoolQueueUpcomingFlowRunsList.vue
src/components/WorkPoolQueuesTable.vue

This PR addresses two areas:
1. Work pool queues were showing late runs for all the queues in a work pool
- This was fixed by renaming a prop from `:work-queue-pool-names` to `":work-pool-queue-names`
2. The state was not being displayed for scheduled flow runs
- This was addressed by using `api.flowRuns.getFlowRuns` since the `/work_pools/{work_pool_name}/get_scheduled_flow_runs` endpoint doesn't return detailed state information. The configured filters for flow runs should return the same flow runs as the `/work_pools/{work_pool_name}/get_scheduled_flow_runs` endpoint, but with detailed state information.

Updates for determining scheduled flow runs for a queue in a work pool

---

src/components/TimezoneSelect.vue

Current: 
Need to know timezone string to set local timezone
New: 
Adds a suggested timezone group and all timezone group and adds localtimezone  as a string when unset is passed as a prop. 
Closes https://github.com/PrefectHQ/orion-design/issues/1062

Enhancement: Add local timezone suggestion when unset and add groups to timezone select

---

src/components/PageHeadingBlocksCatalog.vue
src/localization/locale/en.ts

Adds a link to the collections catalog docs on the blocks catalog page. 
Closes https://github.com/PrefectHQ/prefect/issues/8211
cc @ahuang11

Enhancement: Add a small message about collections to the blocks page

---

src/components/CodeLines.vue
src/utilities/math.ts

using v-bind to allocate sufficient space for each digit place in `lines.length`
tested up to 1000 lines, theoretically should work for any size
open to more elegant css solutions if you know of one
before:
after:

BugFix: line numbers when > 9 lines

---

package-lock.json
package.json

This bumps the graphs dependency. The latest version fixes rendering in Safari and Firefox browsers.
I have tested locally latest graphs -> orion-design -> nebula and confirmed graphs rendered in Safari.

bump graphs dependency to 0.1.14

---

src/components/SchemaPropertyKeyValue.vue

Fixes light-mode contrast issue in block values (specifically json) by switching `CodeHighlighting` component to `CodeSnippet`.
This file could use some clean up, what with the "todo" comments.
Before:
After:

Chore: replaces CodeHighlighting with CodeSnippet

---

src/components/SchemaPropertyBlockKeyValue.vue
src/components/SchemaPropertyKeyValue.vue
src/services/schemas/properties/SchemaPropertyBlock.ts

When creating a block that has an optional block reference it will 500 if that block reference is empty. This is because the mapper was leaving the `null` value in the request when it should be removed from the request completely. 
Also fixes displaying block documents references when viewing a block in the ui.

BugFix: Fix optional block references error

---

src/components/PageHeadingBlocksCatalog.vue

BugFix: Block catalog collections message missing padding

---

src/components/WorkPoolCard.vue

This PR utilizes `media` utility to regulate the position of Late badge for small screens, moving it under the heading

Chore: Move late indicator on small screen under the heading

---

src/components/WorkPoolQueuesDeleteButton.vue
src/components/WorkPoolQueuesTable.vue
src/components/WorkQueueMenu.vue
src/components/WorkQueuesDeleteButton.vue
src/components/WorkQueuesTable.vue

Since all work queues are now part of work pools on the backend, users who still use the work queues page encountered an issue where they tried to delete `default` work queues on that page and can't do that. The reason behind it is that the default queue cannot be deleted. Even though the work queues page will soon be deprecated, this PR fixes the issue for immediate users. The work queues table was rewritten in the same way as the work pool queues table, where default queues cannot be selected for multi-delete and do not have the option to delete them in the menu.

Chore: Hide delete button for default workQueues

---

src/components/FlowRunDetails.vue

Adds an optional hide-radar prop to enable hiding the mini-graph radar for accounts with super large flows. (Should only be temporary and for specific accounts. Currently not an open option.)

Chore: Add an optional prop to hide mini-radar

---

src/router/routes.ts

This PR adds a fix to deploymentFlowRunCreate route to hide query param if there's no param provided

Fix: fix deploymentFlowRunCreate route showing undefined query param

---

src/models/StateType.ts

- Adds `Paused` to the list of cancellable states.  
- Confirmed that this work with no further changes
- some codebase design feedback: calling these states `stuckStateTypes` with the state type models is confusing; "stuck" needs additional context to be a meaningful name.  Maybe something like `cancellableStateTypes` or `nonTerminalStateTypes` that doesn't require explanation
Closes https://github.com/PrefectHQ/prefect/issues/7807

Add paused to cancellable states

---

src/services/WorkspaceWorkPoolQueuesApi.ts
src/services/WorkspaceWorkPoolWorkersApi.ts
src/services/WorkspaceWorkPoolsApi.ts

Removes /experimental prefix from work_pools routes in anticipation of work pools GA release.

Removes experimental prefix from work_pools routes

---

src/localization/locale/en.ts

Adds task input description to localization rather than writing direct into OSS and Cloud.  This allows us to update in one place only and keep things in sync.

Chore:  Add task input info to localization

---

src/components/WorkPoolQueuesTable.vue

This PR updates `ResultCount` to show the correct number when filtered by name search for WorkPoolQueue table

Fix: Update queue result count for WorkPoolQueue table

---

src/components/LogoImage.vue
src/components/PageHeadingBlocksCatalog.vue

Enhancement: Make logo images more visible in dark mode. Add Spacing between block catalog heading and message

---

src/compositions/usePaginatedSubscription.ts
src/utilities/arrays.ts
src/utilities/reactivity.ts

The flow run logs use the flow run id in its filter. Since the flow run itself is on a 5 second interval, reactive effects are triggered every 5 seconds. Since the `usePaginatedSubscription ` composition joins multiple calls together, the reactive effect of the filter empties the response array. 
There used to be a check in place that checked for equality of the watcher's new and old values. But the old and new values [will be the same when deep watching](https://vuejs.org/guide/essentials/watchers.html#deep-watchers) an object. So that [check was removed](https://github.com/PrefectHQ/prefect-ui-library/commit/85afa18c369b5a4bdc86d29d56c12b3f8aaccab5) in order to support the latest filters work. Removing that ensured filter objects were accurate, but also caused paginated subscriptions to …

BugFix: Flow run logs flashing because of polling and subscription reactivity issues

---

package-lock.json
package.json
src/components/FlowRunTimeline.vue
src/components/FlowRunTimelineOptions.vue

Adds recenter and fullscreen buttons. Also includes some keyboard shortcuts.
https://user-images.githubusercontent.com/6776415/218782934-fc37ccfc-b1e7-4552-85b0-5f2895cc6d6a.mov
Note: this will require adding a `position: relative` to the `ContextSidebarLayout` in nebula so it doesn't compete with the sidebar (fixed positioning still constrains it to the parent stacking contexts)

FlowRunTimeline: add recenter and fullscreen buttons

---

src/components/CodeLines.vue

This PR fixes invisible text in light mode
Issue:
https://user-images.githubusercontent.com/40467112/219389636-d40e34ec-1590-448a-b0e7-97957e51e437.mov
<br/>
Now:
https://user-images.githubusercontent.com/40467112/219389698-0819fc89-c086-4ffa-a1f7-f3b8e3a5a8e8.mov
<br/>
The dark mode is not impacted since all text by default has the color white

Chore: fix invisible text in code snippet

---

src/components/SaveFilterModal.vue
src/maps/savedSearchCreate.ts
src/services/WorkspaceSavedSearchesApi.ts

at some point filters changed, and the mapping to CreateSavedSearch was not working
cc @pleek91
source
https://prefect-community.slack.com/archives/C0192RWGJQH/p1677009886310919

BugFix: saved search mapping

---

src/services/Api.ts

cc @pleek91 https://github.com/PrefectHQ/nebula-ui/pull/2435#issuecomment-1439364126
This came to me when thinking about this problem last night. I think this is the best solution because it means developers can continue to not worry about where to put leading/trailing slashes but if we need to make sure a route ends in slash this will not conflict with such logic.

Feature: changed logic for preventing dupe slashes in api

---

src/components/DateRangeInputWithFlowRunHistory.vue
src/components/FlowRunsFilterGroup.vue
src/compositions/filters.ts
src/utilities/object.ts

Fixed several issues here
1. Make sure the date range doesn't return nulls while picking a new range
2. Make sure the default date ranges apply to all components (not just the filters component)
3. Fix `isRecord` utility incorrectly returning `true` when given a `Date`.

BugFix: Flow run filters null dates and recursive filtering

---

src/components/DateRangeInputWithFlowRunHistory.vue

Fixes the "isSame" check to look at the range as a whole rather than the dates individually

BugFix: Flow run filter date range not emitting dates if either start or end is reused

---

src/components/SchemaPropertiesKeyValues.vue
src/components/SchemaPropertyKeyValue.vue
src/components/WorkPoolDetails.vue

Adds display of a work pool's base job configuration to `WorkPoolDetails`.

Feature: Adds display of base job configuration details for work pool

---

src/components/WorkPoolEditForm.vue
src/components/WorkPoolTypeSelect.vue
src/maps/workPool.ts
src/maps/workerCollection.ts
src/models/WorkPoolEdit.ts
src/services/WorkspaceWorkPoolsApi.ts
src/utilities/parameters.ts

Updates `WorkPoolEditForm` to allow changes to the default values for the base job template variables for a work pool. Similar to `WorkPoolCreateForm`, the values from the form are used to set the default values for the `variables` section of the base job template. The starting values for the form fields are taken from the default values in the `variables` section of the base job template for easy editing. The type dropdown for the work pool is displayed, but disabled because a work pool's type cannot be changed after creation.
Note, this PR's base branch is the branch for #1173 due this PR's dependence on work in that PR. I recommend reviewing #1173 first.

Feature: Update work pool edit form to allow updates to the default values for the base job template

---

src/components/WorkPoolCreateForm.vue

Base job configuration values are not being saved correctly because `properties` wasn't being recomputed when updated in the form. This PR makes `parametersMap` reactive to pick up those updates.

Fix: Save base job configuration values correctly

---

src/components/FlowMenu.vue

Currently flows can be deleted from both the UI and the API; however, flows are emergent concepts that are implicitly created whenever runs that reference them are created.  Additionally, flows as an API concept maintain no state (as opposed to deployments, for example, which contain configuration).  Deleting a flow therefore does not _do_ anything, as the flow could re-appear on the next run.  This PR is a part of ongoing reliability work to ensure our object relationships and their mechanics are principled and don't offer ambiguous user experiences.

Remove the ability to delete a flow from UI

---

src/components/FlowRunDetails.vue
src/components/FlowRunListItem.vue

At some point we plan to remove cascading behavior between deployment deletion -> flow run table.  This means that we could end up with flow runs that have populated deployment IDs for deployments that no longer exist.
This PR adjusts the UI to handle that in a more robust way - to be clear, the UI was still working but this makes the display a bit cleaner.
Whoever reviews: I want to make sure that I haven't accidentally increased the number of lookups; I don't believe I have because we were already looking up deployment names for each individual flow run, but I wanted to still check!

Allow graceful handling of flow runs with deleted deployment IDs

---

demo/compositions/useArtifactsMock.ts
demo/compositions/useSeeds.ts
demo/utilities/api.ts
demo/utilities/data.ts
src/maps/artifact.ts
src/mocks/artifact.ts
src/mocks/index.ts
src/mocks/markdown.ts
src/models/Artifact.ts
src/models/api/ArtifactResponse.ts
src/services/WorkspaceArtifactsApi.ts
src/types/SortOptionTypes.ts
src/types/artifact.ts
src/utilities/api.ts

This PR:
- adds support for 4 artifact types: `Result`, `Table`, `Markdown`, and `Unknown` (a catch-all for forwards/backwards compatibility)
- adds markdown mockers
- adds artifact mockers (including basic support for the data fields of known artifact types listed above)
- updates the experimental artifact api endpoint
- fixes filter references in the artifact api

Chore: Artifact mocker and types update

---

demo/sections/states/StateSelect.vue
demo/sections/states/index.ts
src/components/StateBadge.vue
src/components/StateNameSelect.vue
src/components/StateSelect.vue
src/types/stateBadge.ts

Modifies the types for `StateNameSelect` and `StateSelect` to map select values more appropriately. Also creates an independent type for the state badge component

Chore: Fix `StateNameSelect` and `StateSelect` eslint warnings

---

src/components/FlowRunTimeline.vue
src/utilities/eventTarget.ts

This PR fixes an issue where html input keypresses were masked by flow run timeline shortcuts.

Bugfix: Filter hotkey events on flow run timeline 

---

src/components/SchemaFormProperty.vue
src/services/schemas/properties/SchemaPropertyObject.ts
src/services/schemas/properties/SchemaPropertyService.ts

This PR removes `maxLevel` considerations for schema properties and ignores meta-defined rendering in favor of a property-first version that falls back to the same component.
Closes https://github.com/PrefectHQ/prefect/issues/7816

Bugfix: Sub schemas

---

demo/compositions/useFlowRunsMock.ts
demo/compositions/useTaskRunsMock.ts
demo/sections/flowRuns/FlowRunResults.vue
demo/sections/general/ColorModeSelect.vue
netlify.toml
src/components/ArtifactCard.vue
src/components/FlowRunResults.vue
src/localization/locale/en.ts
src/types/flowRunResults.ts
src/utilities/artifactsViewMode.ts

This PR:
- improves mock flow run and task run results artifact description generation (they now more closely resemble action descriptions)
- breaks flow run and task run results into their own lists
- improves some `ArtifactCard` designs
- adds result descriptions to the default slot of `ArtifactCard`s 
- adds an interval to the artifact subscription so results update in real time
- persists a user's list vs grid preference (just using local storage right now but that seemed light enough)
- adds some new demo sections

Enhancement: Flow run results lists

---

src/components/FlowRunResults.vue

Fixes an issue in safari where cards without siblings would expand their height incorrectly if they had a child description
Before:
After:

Bugfix: Safari flow run results card height

---

src/components/SchemaFormProperty.vue

This [PR](https://github.com/PrefectHQ/prefect-ui-library/pull/1222) introduced a bug where block references were being rendered as form inputs rather than a block document input. Fixing that by adding a check specifically for block properties. 
Closes [1229](https://github.com/PrefectHQ/prefect-ui-library/issues/1229)
Before
After

BugFix: Nested blocks not using the block document input

---

src/utilities/timezone.ts

The date-fns proxy that handles timezone conversions was incorrectly returning a function for every property it proxied. This meant that consts like `secondsInHour` were returning a function even though the types would say it was a number.

BugFix: Timezone `dateFunctions` proxy incorrectly returning functions for simple values

---

src/components/FlowRunFilteredList.vue

Make the empty message generic so other projects can determine any more specific messaging or logic

Chore: Make the empty message for a FlowRunFilteredList generic

---

demo/sections/artifacts/ArtifactTimeline.vue
demo/sections/artifacts/index.ts
demo/services/KeyedDataStore.ts
demo/services/mockWorkspaceArtifactsApi.ts
demo/utilities/data.ts
src/components/ArtifactTimeline.vue
src/components/ArtifactTimelineItem.vue
src/localization/locale/en.ts
src/mocks/artifact.ts
src/models/Filters.ts

Introduces 2 WIP components we'll be using for showing lineage-type data for artifacts. The `ArtifactCollectionTimelineItem` I expect to change/evolve quite a bit in the next week so I've intentionally not spent much time cleaning it up. I also took a crack at filters for the artifacts mock api that should work nicely for gets and counts

Feature: `ArtifactCollectionTimeline` and `ArtifactCollectionTimelineItem` components

---

package-lock.json
package.json
vite.config.ts

nebula-ui has vue-charts as a dependency. Which means there can be version mis matches that cause things like css to not appear to be updating. Making vue-charts a peer would solve this and also reduce the bundle size by not bundling vue-charts twice. 
oss ui does not have vue-charts as a dependency and this change would require it to. But that shouldn't be an issue.

Chore: Make vue-charts a peer dependency

---

src/compositions/filters.ts
src/maps/filters.ts
src/models/Filters.ts
src/models/api/Filters.ts
src/services/WorkspaceBlockDocumentsApi.ts

Enables request batching for individual block document requests. Something to note is the `isAnonymous: null` part of the filter. This ensures that both anonymous and non anonymous blocks are returned.

Enhancement: Batch block document get requests

---

src/components/ArtifactResultCard.vue
src/components/DeploymentIconText.vue
src/components/FlowIconText.vue
src/components/FlowRouterLink.vue
src/components/FlowRunDetails.vue
src/components/FlowRunIconText.vue
src/components/FlowRunListItem.vue
src/components/LogRow.vue
src/components/NotificationForm.vue
src/components/PageHeadingArtifact.vue
src/components/WorkQueueDetails.vue
src/components/WorkQueueLastPolled.vue
src/components/WorkQueueLateIndicator.vue
src/components/WorkQueueStatusBadge.vue
src/components/WorkQueueStatusIcon.vue
src/compositions/useBlockDocument.ts
src/compositions/useBlockSchema.ts
src/compositions/useBlockType.ts
src/compositions/useDeployment.ts
src/compositions/useFlow.ts
src/compositions/useFlowRun.ts
src/compositions/useTaskRun.ts
src/compositions/useTaskRunsCount.ts
src/compositions/useWorkPoolQueue.ts
src/compositions/useWorkQueueStatus.ts
src/types/useEntitySubscription.ts

This would be a breaking change and would require updating everywhere we currently do `const flowRun = useFlowRun(flowRunId)` to be `const { flowRun } = useFlowRun(flowRunId)`
The motivation for this change is currently there is no way to know if the api request actually succeed or failed. Exposing the underlying subscription allows the most flexibility at implementation.

Enhancement: Expose subscription in useFlowRun and similar compositions

---

src/models/BatchLookupError.ts
src/models/index.ts
src/services/BatchProcessor/BatchProcessor.ts

Adds a new BatchLookupError that is used to reject batch process calls if the value is undefined. Previously the return type from the map was being ignored with a `!`. Which meant in our api services if the `/filter` endpoint didn't return a value for an id the batch processes would incorrectly resolve as successful but with an `undefined` value.

BugFix: Reject batch process promises if value is undefined

---

package-lock.json
package.json
tailwind.config.js

Tailwind 3.3.0 includes the line clamp utilities by default and deprecated this plugin. 
https://tailwindcss.com/blog/tailwindcss-v3-3#line-clamp-out-of-the-box

Chore: Remove deprecated tailwind line clamp plugin

---

src/services/WorkspaceVariablesApi.ts

Implements the variables API as it (mostly) exists right now; note that the `delete` and `edit` services are subject to change since those aren't done yet but I don't think they will do so significantly. I didn't include the bulk get/filter route since that's also WIP and I don't want to implement the filter models until I've seen the API (we've agreed on one but that can change during implementation)

Feature: VariablesWorkspaceAPI service

---

demo/compositions/useArtifactsMock.ts
demo/compositions/useSeeds.ts
demo/services/MockApi.ts
demo/services/mockWorkspaceArtifactsApi.ts
demo/utilities/api.ts
demo/utilities/data.ts
src/components/ArtifactCollections.vue
src/components/ArtifactKeyIconText.vue
src/components/ArtifactTimeline.vue
src/components/PageHeadingArtifact.vue
src/maps/artifact.ts
src/maps/filters.ts
src/maps/index.ts
src/models/ArtifactCollection.ts
src/models/Filters.ts
src/models/api/ArtifactCollectionResponse.ts
src/models/api/Filters.ts
src/models/index.ts
src/router/index.ts
src/router/routes.ts
src/services/WorkspaceArtifactsApi.ts

This PR adds more explicit support for artifact collections (containing objects for the `latest` artifact of a given key) and drops support for `is_latest` in the artifacts filter route. Updates all relevant components to use the new route

Chore: Artifact collections

---

demo/sections/artifacts/ArtifactCard.vue
src/components/ArtifactCard.vue
src/components/ArtifactCollections.vue

This PR moves the default slot from the `ArtifactCard` component to instead wrap the existing summary item and adds additional slot for taking advantage of the summary row formatting. The default slot as previously implemented was a vestige of an earlier design and isn't used anywhere.

Enhancement: Artifact card default slot

---

src/components/WorkPoolDetails.vue
src/models/WorkPool.ts
src/services/schemas/properties/SchemaPropertyAny.ts
src/services/schemas/properties/SchemaPropertyBlock.ts
src/services/schemas/resolvers/blockReferenceDefaults.ts
src/services/schemas/resolvers/defaults.ts
src/services/schemas/resolvers/definitions.ts
src/services/schemas/resolvers/schemas.ts
src/services/schemas/utilities.ts
src/utilities/parameters.ts

Adds a new resolver for schemas that resolved default values properties that have block document references. As well as accounts for properties that are type `block` that might have a default value. 
Supersedes: https://github.com/PrefectHQ/prefect-ui-library/pull/1324

Enhancement: Account for block document references with default values when resolving schemas

---

src/components/FlowRunTimeline.vue

Resolves PrefectHQ/graphs#126
When holding `control+f` to 'find all', the graph was going full screen. This makes it so the keyboard shortcuts aren't fired if a meta key (control/command/etc) is also held.

prevent flow graph shortcuts when metakey

---

src/components/SchemaFormProperties.vue
src/services/schemas/properties/SchemaPropertyService.ts
src/services/schemas/resolvers/meta.ts
src/types/schemas.ts

Fixes two issues with schema resolving
- Object properties were only considered required if they had required child properties. This is incorrect and required should always be determined by the parent property
- `allOf` and `anyOf` references should inherit the required value of the property they are associated with. Was previously hard coded to `false`
Need to do some more regression testing on this. 
Closes https://github.com/PrefectHQ/prefect/issues/9055

BugFix: Schema form incorrectly marking reference objects as optional

---

src/components/LogRow.vue

BugFix: Allow log messages to break long words to preserve container width

---

src/components/LogRow.vue

Follow up from https://github.com/PrefectHQ/prefect-ui-library/pull/1334 which didn't quite address the issue. Was able to reproduce thanks to https://github.com/PrefectHQ/prefect-ui-library/issues/1341
Closes https://github.com/PrefectHQ/prefect-ui-library/issues/1341
Before
After

BugFix: Logs overflow container

---

src/components/FlowRunDeployment.vue
src/components/FlowRunDetails.vue
src/components/FlowRunListItem.vue
src/components/FlowRunTaskCount.vue
src/components/FlowRunWorkPool.vue
src/components/FlowRunWorkQueue.vue
src/components/PageHeadingFlowRun.vue
src/models/StateType.ts

Updates the FlowRunPageHeader to include top level meta details consistent with the FlowRunListItem. FlowRunDetails have also been updated to remove duplicate information.
Once this is deployed and updates are made in OSS and Nebula, the result will look like these examples:
A flow run has completed and has no worker/deployment/etc:
A flow run has not ran yet:

update FlowRunPageHeader and FlowRunDetails for full page layout

---

src/components/WorkPoolBaseJobTemplateFormSection.vue
src/services/schemas/properties/SchemaPropertyArray.ts
src/services/schemas/properties/SchemaPropertyObject.ts
src/services/schemas/properties/SchemaPropertyService.ts
src/services/schemas/properties/SchemaPropertyString.ts

Default values were not showing the `WorkPoolDetails` component despite being present in the base job template. This PR updates the Schema Property services to pull default values from their respective properties.

Updates retrieval of default values for schemas

---

package-lock.json
package.json
src/components/FlowRunTimeline.vue

This PR removes the popout from the flow run timeline. The `selectedNode` state will be managed by the parent now.
Also bumps the vue-charts dependency in prep for what I'll need in Nebula.
NOTE: Nebula and OSS will need fallowup PR's once this is merged. I won't merge it until I have those ready.

Remove popout from flow run timeline

---

src/components/DeploymentForm.vue
src/components/JsonInput.vue
src/components/SchemaFormInput.vue
src/localization/locale/en.ts
src/services/schemas/properties/SchemaPropertyArray.ts
src/services/schemas/utilities.ts

This PR makes some minor improvements to deployment forms and fixes a few long standing issues with schemas. One bigish change is the removal of `PSelect` in list properties; this is to work around some incompatibilities between the component and the intent of list properties (in particular duplicate values and ordering)

Enhancement: Schema / deployment form

---

src/services/schemas/properties/SchemaPropertyBoolean.ts

This PR overrides the request value mapper from the base schema property service class for boolean values; this will ensure that form toggles are respected even when they match the default in the schema (previously these were falling back to runtime values)

Bugfix: Boolean schema property incorrect mapping when defaults match value

---

src/components/SchemaFormInput.vue
src/services/schemas/properties/SchemaPropertyArray.ts
src/services/schemas/utilities.ts

This PR makes two important changes to the way array values are mapped in schemas:
1. The property array response mapper first checks if a value is already a JSON string before attempting to stringify it for use in code input components
2. Schemas attempt to parse a value when deciding which union property to display
There's still a bug here where validators for fieldsets in the union will apply to the incorrect member, but I'm working on that

Bugfix: `anyOf` and `array` schema mapping

---

src/components/FlowRunTimeline.vue

Just some logic I noticed that we could use a utility for.

Chore: Use utility for `isRunning` in FlowRunTimeline

---

src/components/FlowList.vue

The `FlowList` component was incorrectly passing just its base filter to its list items. This PR instead passes the route filter which includes the base filter and any additional user-supplied filters.

Bugfix: Route filter should be passed to flow list items

---

src/components/DeploymentForm.vue
src/components/DeploymentParameters.vue
src/components/QuickRunParametersModal.vue

Uses the prop parameters instead of deployment.parameters to set the values in the deployment form and flow run create form.  Fixes a bug introduced by #1407 which ignored values passed by the "copy to new run" button.

Bugfix: Fix use of model value in deployment parameters component

---

src/services/BatchProcessor/BatchProcessor.ts

Fixes the `cannot access "mocks" before initialization` error we were seeing in the demo app

Chore: Fix export in BatchProcessor that caused circular references

---

src/services/storage/useStorage.ts

I noticed some errors around storage on the flow run page. They were caused by returning the storage methods directly from the composition rather than wrapping them in arrow function to preserve context.

BugFix: Fix `useStorage` composition destroying the storage context

---

src/components/WorkPoolQueueStatusIcon.vue

Updating these indicators in preparation for the new Dashboard view. The previous icons used for healthy and unhealthy appeared interactive/clickable (similar to a dismiss button or radio). This makes them more generic. The green dot is intended to be more passive than an illustrative icon. Distinction is maintained between each for accessibility (e.g. a red dot may not be visibly distinguishable from a green dot to certain users).
New healthy dark:
New healthy light:
New unhealthy dark:
New unhealthy light:
New paused dark:
New paused light:

update work pool health indicator

---

src/components/FlowRunTimeline.vue

This PR fixes an issue where the timeline wasn't properly inverting colors it received from the `getStateTypeStyles` utility. It also passes a debounced theme ref to avoid a race condition where the theme has changed but the sample elements have not (yet).
Before:
After:

Bugfix: Washed out flow run timeline view

---

src/components/StateListItem.vue

`disabled` was used to prevent the checkbox from animating in and being clickable. This change keeps respects that expectation, but actually removes a checkbox from view when it's disabled.

hide checkbox on disabled
