PrefectHQ/prefect-ui-library

- src/components/RadarApp.vue
- src/components/RadarNodeTaskRun.vue
- src/models/TaskRun.ts
This PR addresses an issue where Radar wasn't updating appropriately, requiring a refresh to get run results. It also slightly tweaks the method used to compute task run duration. 
Closes: https://github.com/PrefectHQ/prefect/issues/7660
> Bugfix: Radar app + node refreshes

- src/components/FlowRunSubFlows.vue
Closes https://github.com/PrefectHQ/prefect/issues/7795
> BugFix: Subflow state filter returns 0 results

- package.json
I believe this is why dependabot isn't picking up the changelog in bump prs
> Chore: Add the repo urls to the package.json

- demo/sections/workers/WorkerHeadings.vue
- demo/sections/workers/index.ts
- src/components/PageHeadingWorkerPool.vue
- src/components/index.ts
- src/mocks/workerPool.ts
This PR adds a `PageHeadingWorkerPool` component that incorporates existing `WorkerPoolToggle` and `WorkerPoolMenu` components. 
It also adds a new section for worker pool headings to the demo application for easier review.
> Feature: Worker Pool header component

- package-lock.json
- package.json
- src/components/FlowRunTimeline.vue
- src/models/TimelineNode.ts
Bumps the `@prefecthq/graphs` dependency and fixes a couple related bugs.
> bump graphs and fix bugs

- src/utilities/variables.ts
per suggestion here
https://github.com/PrefectHQ/prefect/pull/7965/files#r1057885854
this felt like the best place for such a type guard
> Chore: added isNotNullish type guard per code review suggestion

- package-lock.json
- package.json
- src/components/BlockSchemaCapabilitySelect.vue
- src/components/BlockTypeSelect.vue
- src/components/ColorModeSelect.vue
- src/components/LogLevelSelect.vue
- src/components/StateNameSelect.vue
- src/components/StateSelect.vue
- src/components/WorkerPoolTypeSelect.vue
- src/models/StateType.ts
p-select [recently changed](https://github.com/PrefectHQ/prefect-design/pull/561), this PR addresses the breaking change from that
> BugFix: Support for latest prefect design

- src/components/WorkerPoolQueuesTable.vue
> Chore: Add "Add queue" button

- demo/compositions/useBlockSchemaMock.ts
- demo/sections/blocks/BlockCapabilityBlockDocumentInput.vue
- demo/sections/blocks/index.ts
- demo/services/mockWorkspaceBlockDocumentsApi.ts
- src/components/BlockCapabilityBlockDocumentInput.vue
- src/maps/blockDocumentFilter.ts
- src/models/BlockDocumentFilter.ts
- src/models/api/BlockDocumentFilterRequest.ts
Adds a new component for selecting a block document from a list of block documents with the same capability. Almost identical in appearance and functionality to the BlockDocumentInput component except it accepts a capability rather than a block type.
> Feature: BlockCapabilityBlockDocumentInput component

- src/components/BlockCapabilityBlockDocumentInput.vue
- src/components/BlockDocumentsSelect.vue
- src/components/index.ts
Moves the logo inside the select
Exports the component
> Enhancement: Improve layout of the BlockCapabilityBlockDocumentInput

- demo/compositions/useFlowRunGraphMock.ts
- demo/compositions/useSeeds.ts
- demo/compositions/useTaskRunsMock.ts
- demo/sections/flowRuns/FlowRunRadar.vue
- demo/sections/flowRuns/index.ts
- demo/services/MockApi.ts
- demo/services/mockWorkspaceFlowRunsApi.ts
- demo/types/flowRunGraphMock.ts
- demo/utilities/api.ts
- demo/utilities/data.ts
- src/mocks/flowRunGraph.ts
^Also adds a flow run radar demo
> Chore: useFlowRunGraphMock, useTaskRunMock

- src/components/FlowMenu.vue
Fixed by tweaking the slot position in the template
> Chore: Make sure delete is the last menu item in the FlowMenu

- src/components/RadarNode.vue
Adds a small border to radar nodes for better visual clarity:
Before:
After:
> Enhancement: Radar border

- demo/sections/index.ts
- demo/sections/logs/RunLogs.vue
- demo/sections/logs/index.ts
- src/components/LogLevelLabel.vue
- src/components/LogRow.vue
- src/components/LogsContainer.vue
- src/components/RadarNode.vue
Fixes some issues with logs on dark backgrounds
> Enhancement: Add logs demo, minor style tweaks

- package-lock.json
- package.json
- src/components/BlockCapabilityBlockDocumentInput.vue
- src/components/DeploymentCombobox.vue
Group the block documents by their block type
> Enhancement: Group blocks by type in the BlockCapabilityBlockDocumentInput

- src/components/PageHeadingWorkPools.vue
- src/components/WorkPoolCard.vue
- src/components/WorkPoolCreateForm.vue
- src/components/WorkPoolDetails.vue
- src/components/WorkPoolEditForm.vue
- src/components/WorkPoolQueueDetails.vue
This PR removes workPool types since we don't want to introduce them to users just yet
> Chore: Remove workPool types

- package-lock.json
- package.json
- src/components/RadarApp.vue
- src/components/RadarSmall.vue
This PR bumps Radar to 0.0.19 and makes adds the new color accessor to rings. 
Fixes: https://github.com/PrefectHQ/nebula-ui/issues/2278
> Chore & Bugfix: Radar rings

- src/maps/deployment.ts
- src/mocks/deployment.ts
- src/models/Deployment.ts
- src/models/api/DeploymentResponse.ts
Part of https://github.com/PrefectHQ/prefect/issues/8271
> Chore: Add infraOverrides to Deployment model

- src/services/schemas/properties/SchemaPropertyAny.ts
- src/services/schemas/resolvers/definitions.ts
- src/services/schemas/utilities.ts
- src/utilities/cache.ts
Treats `allOf` references the same as `anyOf`. 
Closes https://github.com/PrefectHQ/orion-design/issues/1102
> BugFix: Fix anyOf schema block references

- src/components/WorkPoolQueuesTable.vue
- src/components/WorkQueueIconText.vue
- src/maps/workQueue.ts
- src/mocks/workQueue.ts
- src/models/WorkQueue.ts
- src/models/api/WorkQueueResponse.ts
In this PR WorkQueueIconText was updated to redirect to the pool queue
Also where necessary 'Queue' was changed to 'Work Queue'
> Chore: Update workQueue, WorkQueueIconText, and changed Queue => Work Queue wording

- src/utilities/dates.ts
Just adding a missing date format utility
> Enhancement: Add a date numeric format

- src/components/FlowRunListItem.vue
> Chore: Update WorkPool and WorkQueue rendering in FlowRunListItem

- src/components/WorkPoolQueueUpcomingFlowRunsList.vue
This PR updates the filter for upcoming runs for the pool queue to the new pattern and makes sure it works correctly
> Bugfix: Update filter in WorkPoolQueueUpcomingFlowRunsList to follow new pattern

- src/maps/artifact.ts
- src/maps/filters.ts
- src/maps/index.ts
- src/models/Artifact.ts
- src/models/Filters.ts
- src/models/api/ArtifactResponse.ts
- src/models/api/Filters.ts
- src/models/api/index.ts
- src/models/index.ts
- src/services/WorkspaceArtifactsApi.ts
- src/types/SortOptionTypes.ts
This is most of the services and classes we'll need for the mvp artifacts build out
> Feature: Artifacts API

- src/components/SchemaPropertyKeyValue.vue
Was: 
Now:
Closes https://github.com/PrefectHQ/prefect-ui-library/issues/1104
> Bugfix: Fix json overflowing

- src/maps/filters.ts
- src/models/Filters.ts
- src/models/api/Filters.ts
- src/services/WorkspaceDeploymentsApi.ts
- src/services/WorkspaceFlowsApi.ts
- src/services/WorkspaceTaskRunsApi.ts
- src/services/WorkspaceWorkQueuesApi.ts
Following the pattern set in WorkspaceFlowRunsApi I'm adding batch processing of individual get requests to a few other services. Also fixed a filter that wasn't quite right.
> Enhancement: Add batch processing to more api services

- package-lock.json
- package.json
- src/components/FlowRunFilteredList.vue
fixes this bg color in Deployments, Flow, WorkPool, and WorkPoolQueue
also uses latest prefect-design
> Feature: Light mode bg

- src/compositions/useTabs.ts
Part of the fix for https://github.com/PrefectHQ/nebula-ui/issues/1860
> Enhancement: Update useTabs to be aware of the selected tab

- demo/sections/logs/RunLogs.vue
- src/components/LogRow.vue
- src/mocks/index.ts
- src/mocks/log.ts
- src/mocks/string.ts
Adds logger names to the log row component (trailing content)
> Enhancement: Logger names

- demo/sections/deployments/DeploymentDescription.vue
- demo/sections/deployments/index.ts
- src/components/DeploymentDescription.vue
- src/components/DeploymentForm.vue
Uses the new p-markdown-renderer component on deployment descriptions to enhance the deployment experience. 
https://www.loom.com/share/d9aa7ca19c0143e49819a03ec93f7fb6
> Enhancement: Use markdown renderer for deployment descriptions

- src/components/WorkPoolCreateForm.vue
- src/components/WorkPoolDetails.vue
- src/components/WorkPoolEditForm.vue
- src/components/WorkersTable.vue
- Adds a beta tag to the 'Base Job Configuration' section of work pool forms
- Adds a description to type field in work pool create form
- Defaults new work pools to `Prefect Agent` type
- Adds beta messaging to workers table
> Updates for workers beta

- package-lock.json
- package.json
- src/components/FlowRunDetails.vue
- src/maps/flowRun.ts
- src/mocks/flowRun.ts
- src/models/FlowRun.ts
- src/models/api/FlowRunResponse.ts
Organizes the flow run details component and adds headings to sections. Closes https://github.com/PrefectHQ/prefect/issues/8635
After
Before
> Enhancement: Update the flow run details component

- src/components/FlowRunFilteredList.vue
Adds a slot so oss and cloud and customize the message. Leaving the existing message as the default value of the slot until all the implementations have been updated.
> Enhancement: Allow the empty message for FlowRunFilteredList to be overridden at implementation

- src/components/FlowRunResults.vue
- src/localization/locale/en.ts
Note for reviewers: decided to try something slightly new here, using the markdown renderer for localization content; seems to work nicely but also open to other suggestions.
> Enhancement: No results messages link to docs

- src/components/FlowRunBreadCrumbs.vue
- src/components/FlowRunListItem.vue
- src/components/FlowRunPopOverContent.vue
- src/components/StateListItem.vue
Closes https://github.com/PrefectHQ/prefect-ui-library/issues/824
> Enhancement: Make flow run bread crumbs consistent

- src/services/schemas/properties/SchemaPropertyService.ts
Closes https://github.com/PrefectHQ/prefect/issues/7623
Makes sure any json input is validated as valid json before submitting
> Enhancement: Validate any schema property that is a JsonInput has valid json

- src/components/FlowRunDetails.vue
The state message was removed from the flow run details in #1214
Adding it back since there isn't currently another place to view it
> Enhancement: Add the state message to the flow run details

- src/index.ts
Follow up of https://github.com/PrefectHQ/prefect-ui-library/pull/1255
> Chore: Remove vue-charts css from bundle

- src/components/ArtifactCollections.vue
Technically this won't work without a few backend PRs but doesn't hurt to fix now
> Bugfix: Make sure collections only fetch the latest artifact

- demo/sections/artifacts/ArtifactDataView.vue
- demo/sections/artifacts/index.ts
- src/components/ArtifactDataTable.vue
- src/components/ArtifactDataView.vue
- src/localization/locale/en.ts
- src/mocks/artifact.ts
- src/mocks/index.ts
- src/mocks/table.ts
This PR:
- adds a new renderer for artifacts
- fixes a few issues with the artifact mocker
- adds a new mock generator for tabular data
> Feature: Artifact table renderer

- src/components/VariableCreateModal.vue
- src/components/VariableEditModal.vue
- src/models/Variable.ts
Related to https://github.com/PrefectHQ/nebula/pull/4295
Closes: #1301
> Chore: Move max chars to the variable model, separate value and name limits

- src/utilities/arrays.ts
Utility for easily toggling a value in an array. Works similar to `classList.toggle`
> Feature: Array `toggle` utility

- src/components/FlowRunTimeline.vue
- src/components/FlowRunTimelineSubFlowRunDetails.vue
- src/components/FlowRunTimelineTaskDetails.vue
Add the flow name along side the flow-run name for sub-flow-runs.
Related to PrefectHQ/prefect#8969
> add flow name to sub flows on flow run graph

- package-lock.json
- package.json
- src/components/ArtifactTimeline.vue
> Chore: Fix dev and server errors

- src/components/TaskRunArtifacts.vue
- src/localization/locale/en.ts
Related: https://github.com/PrefectHQ/nebula-ui/issues/2626
> Feature: `TaskRunArtifacts` component

- src/components/ArtifactTimeline.vue
- src/compositions/useArtifactCollection.ts
> Enhancement: Artifact collection composition

- src/components/SchemaPropertiesKeyValues.vue
- src/components/SchemaPropertyKeyValue.vue
Closes https://github.com/PrefectHQ/prefect/issues/9186
Before
After
> BugFix: Block document json now filling available space

- src/components/FlowRunMenu.vue
Closes https://github.com/PrefectHQ/prefect/issues/8854
> Enhancement: Update the flow run menu "Custom run" to "Copy to new run"

- src/components/DeploymentForm.vue
- src/services/schemas/properties/SchemaPropertyService.ts
Resolves: https://github.com/PrefectHQ/prefect/issues/9248
> Bugfix: Invalid schema values mapping

- src/components/DeploymentsTable.vue
Before:
After:
Closes https://github.com/PrefectHQ/prefect/issues/9272 
Closes https://github.com/PrefectHQ/prefect/issues/8791
> Enhancement: Add options to the deployment tags select

- src/components/DeploymentDetails.vue
Closes https://github.com/PrefectHQ/prefect-ui-library/issues/1242
> Enhancement: Display deployment entrypoint and path in deployment details tab

- src/components/WorkPoolTypeSelect.vue
- src/utilities/processTypes.ts
> Enhancement: Better work pool process type labels

- src/components/TimezoneSelect.vue
Closes https://github.com/PrefectHQ/prefect-ui-library/issues/1066
Before
After
> Enhancement: Format timezone labels

- src/components/CollectionItemCard.vue
- src/components/DeploymentCombobox.vue
- src/components/FlowCombobox.vue
- src/components/WorkQueueCombobox.vue
- src/compositions/useStatePolling.ts
- src/services/schemas/properties/SchemaPropertyString.ts
- src/utilities/object.ts
Just a lint roller rolling on by
> Chore: Lint fixes

- demo/services/mockCollectionsApi.ts
- demo/services/mockHealthApi.ts
- demo/services/mockUiApi.ts
- demo/services/mockWorkspaceLogs.ts
- demo/services/mockWorkspaceNotificationsApi.ts
- demo/services/mockWorkspaceSavedSearchesApi.ts
- demo/services/mockWorkspaceVariablesApi.ts
- demo/utilities/api.ts
- package-lock.json
- package.json
- src/components/ConfirmDeleteModal.vue
- src/components/ConfirmStateChangeModal.vue
- src/components/CronScheduleForm.vue
- src/components/IntervalScheduleForm.vue
- src/components/ResultsCount.vue
- src/components/SearchInput.vue
- src/components/SelectedCount.vue
- src/components/StateIcon.vue
- src/components/SubmitButton.vue
- src/services/CollectionsApi.ts
- src/services/HealthApi.ts
- src/services/UiApi.ts
- src/services/WorkspaceLogsApi.ts
- src/services/WorkspaceNotificationsApi.ts
- src/services/WorkspaceSavedSearchesApi.ts
Keeping with the other projects. Updating revealed an error in our mock api. Not worth implementing the actual api methods but I added mock services with not implemented methods to satisfy the types and so the next person that tries to use this is left with a clean slate.
> Chore: Update vue to 3.3.4

- src/localization/locale/en.ts
Closes https://github.com/PrefectHQ/prefect/issues/9620
> Fix: Update link to docs notifications

- .eslintrc.json
- .github/actions/setup/action.yaml
- .github/workflows/tests.yaml
- package-lock.json
- package.json
- src/services/schemas/constants.spec.ts
This PR introduces vitestest to the project and updates our actions workflows to run the test suite on every PR. 
Resolves: #1443
> Chore: Vitetest setup

- src/components/FlowRunTimeline.vue
- src/types/states.ts
- src/utilities/state.ts
Closes https://github.com/PrefectHQ/prefect/issues/9689
- Adds "Skipped" state
- Fixes "Retrying" state
- Uses consistent colors for states on the timeline rather than hard coding everything to the `600` shade.
> BugFix: Unknown states crash flow run timeline

- src/components/TaskRunDetails.vue
Closes https://github.com/PrefectHQ/prefect/issues/8632
> Enhancement: Organize and update task run details

- src/services/can.ts
Starting point for other projects to implement.
> Chore: Add `dashboard` feature flag

- src/router/index.ts
- src/router/routes.ts
Added here for implementation in oss and cloud
> Chore: Add workspace dashboard route

- demo/sections/dashboard/DashboardTimeSpanFilter.vue
- demo/sections/dashboard/index.ts
- demo/sections/index.ts
- src/components/DashboardTimeSpanFilter.vue
Filter component for changing the time span that the dashboard shows.
> Feature: DashboardTimeSpanFilter

- package-lock.json
- package.json
- src/components/StateListItem.vue
This updates StateListItem so that it works with the changes made [here](https://github.com/PrefectHQ/prefect-design/pull/818). Also, if no value is defined for the selected behavior, render the component without a checkbox.
> bump prefect-design, update StateListItem

- package-lock.json
- package.json
Update to latest prefect-design
> Chore: Update prefect-design
